{
 "title": "Destination-Comparison Benchmarks",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "selected_benchmark_uuid",
    "label": "Benchmark UUID",
    "query": "SELECT benchmark_uuid , value FROM \"runtime_seconds\" WHERE \"benchmark_type\" =  '<class \\'benchmark.DestinationComparisonBenchmark\\'>'"
   },
   {
    "name": "selected_workflow_name",
    "label": "Workflow",
    "query": "SELECT workflow_name, value FROM \"runtime_seconds\" WHERE \"benchmark_type\" =  '<class \\'benchmark.DestinationComparisonBenchmark\\'>' GROUP BY workflow_name"
   },
   {
    "name": "selected_destination_name",
    "label": "Destination",
    "query": "SELECT destination_name, value FROM \"runtime_seconds\" WHERE \"benchmark_type\" =  '<class \\'benchmark.DestinationComparisonBenchmark\\'>' GROUP BY destination_name"
   },
   { "name": "selected_measurement", "label": "Measurement", "query": "SHOW MEASUREMENTS " }
  ]
 },
 "panels": [
  {
   "title": "Custom Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow Status",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_benchmark_uuid: $col",
       "groupBy": [
        { "params": [ "benchmark_uuid" ], "type": "tag" }
       ],
       "measurement": "workflow_status",
       "query": "SELECT success, error FROM (SELECT count(\"value\") as success FROM \"workflow_status\" WHERE (\"value\" = 'success') AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/ AND $timeFilter GROUP BY \"benchmark_uuid\"), (SELECT count(\"value\") as error FROM \"workflow_status\" WHERE (\"value\" = 'error')  AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/ AND $timeFilter GROUP BY \"benchmark_uuid\") GROUP BY benchmark_uuid",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        { "key": "value", "operator": "=", "value": "error" }
       ]
      }
     ]
    },
    {
     "title": "Selected Measurements",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT value FROM /$selected_measurement/  WHERE (\"benchmark_type\" =  '<class \\'benchmark.DestinationComparisonBenchmark\\'>' AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/) AND $timeFilter GROUP BY benchmark_uuid, destination_name, workflow_name",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Average over selected measurements",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT min(\"sum\"), max(\"sum\"), mean(\"sum\"), stddev(\"sum\") FROM (SELECT sum(\"value\") FROM /$selected_measurement/ WHERE (\"benchmark_type\" =  '<class \\'benchmark.DestinationComparisonBenchmark\\'>' AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/) AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\") GROUP BY \"benchmark_uuid\", \"destination_name\", \"workflow_name\" ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Runtime",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "staging_time",
     "query": "SELECT sum(\"value\") FROM \"runtime_seconds\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.DestinationComparisonBenchmark\\'>' AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/) AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  },
  {
   "title": "Average Runtime per Benchmark, Destination and Workflow",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "staging_time",
     "query": "SELECT min(\"sum\"), max(\"sum\"), mean(\"sum\"), stddev(\"sum\") FROM (SELECT sum(\"value\") FROM \"runtime_seconds\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.DestinationComparisonBenchmark\\'>' AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/) AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\") GROUP BY \"benchmark_uuid\", \"destination_name\", \"workflow_name\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  },
  {
   "title": "Average Runtime per Destination and Workflow",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "staging_time",
     "query": "SELECT min(\"sum\"), max(\"sum\"), mean(\"sum\"), stddev(\"sum\") FROM (SELECT sum(\"value\") FROM \"runtime_seconds\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.DestinationComparisonBenchmark\\'>' AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/) AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"history_name\") GROUP BY destination_name, workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  },
  {
   "title": "Average Runtime per Destination and Workflow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_destination_name: $tag_workflow_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"sum\") FROM (SELECT sum(\"value\") FROM \"runtime_seconds\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.DestinationComparisonBenchmark\\'>' AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/) AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"history_name\") WHERE $timeFilter GROUP BY destination_name, workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Workflow Runtime",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "staging_time",
     "query": "SELECT value FROM \"total_workflow_runtime\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.DestinationComparisonBenchmark\\'>' AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/) AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  },
  {
   "title": "Average Total Workflow Runtime per Benchmark, Destination and Workflow",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "staging_time",
     "query": "SELECT min(\"value\"), max(\"value\"), mean(\"value\"), stddev(\"sum\") FROM (SELECT value FROM \"total_workflow_runtime\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.DestinationComparisonBenchmark\\'>' AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/) AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\") GROUP BY \"benchmark_uuid\", \"destination_name\", \"workflow_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  },
  {
   "title": "Average Total Workflow Runtime per Destination and Workflow",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "staging_time",
     "query": "SELECT min(\"value\"), max(\"value\"), mean(\"value\"), stddev(\"sum\") FROM (SELECT value FROM \"total_workflow_runtime\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.DestinationComparisonBenchmark\\'>' AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/) AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"history_name\") GROUP BY  \"destination_name\", \"workflow_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  },
  {
   "title": "Average Total Workflow Runtime per Destination and Workflow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_destination_name: $tag_workflow_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM (SELECT value FROM \"total_workflow_runtime\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.DestinationComparisonBenchmark\\'>' AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/) AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\") WHERE $timeFilter GROUP BY \"benchmark_uuid\", \"destination_name\", \"workflow_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "CPU Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CPU-Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "cpuacct.usage",
     "query": "SELECT sum(\"value\") FROM \"cpuacct.usage\" WHERE (\"benchmark_type\" = '<class \\'benchmark.DestinationComparisonBenchmark\\'>' AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/) AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  },
  {
   "title": "Average CPU-Usage per Benchmark, Destination and Workflow",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "cpuacct.usage",
     "query": "SELECT min(\"sum\"), max(\"sum\"), mean(\"sum\"), stddev(\"sum\") FROM (SELECT sum(\"value\") FROM \"cpuacct.usage\" WHERE (\"benchmark_type\" = '<class \\'benchmark.DestinationComparisonBenchmark\\'>' AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/) AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\") GROUP BY \"benchmark_uuid\", destination_name, workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  },
  {
   "title": "Average CPU-Usage per Destination and Workflow",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "cpuacct.usage",
     "query": "SELECT mean(\"sum\") FROM (SELECT sum(\"value\") FROM \"cpuacct.usage\" WHERE (\"benchmark_type\" = '<class \\'benchmark.DestinationComparisonBenchmark\\'>' AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/) AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"history_name\") WHERE $timeFilter GROUP BY destination_name, workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  },
  {
   "title": "Average CPU-Time per Destination and Workflow",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "$tag_destination_name: $tag_workflow_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"sum\") FROM (SELECT sum(\"value\") FROM \"cpuacct.usage\" WHERE (\"benchmark_type\" = '<class \\'benchmark.DestinationComparisonBenchmark\\'>' AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/) AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"history_name\") WHERE $timeFilter GROUP BY destination_name, workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Staging Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Staging-Time per Workflow-Run",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"staging_time\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.DestinationComparisonBenchmark\\'>' AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/) AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Staging-Time per Benchmark, Destination and Workflow",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "staging_time",
     "query": "SELECT min(\"sum\"), max(\"sum\"), mean(\"sum\"), stddev(\"sum\") FROM (SELECT sum(\"value\") FROM \"staging_time\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.DestinationComparisonBenchmark\\'>' AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/) AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\") GROUP BY benchmark_uuid, destination_name, workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  },
  {
   "title": "Average Staging-Time per Destination and Workflow",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "staging_time",
     "query": "SELECT min(\"sum\"), max(\"sum\"), mean(\"sum\"), stddev(\"sum\") FROM (SELECT sum(\"value\") FROM \"staging_time\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.DestinationComparisonBenchmark\\'>' AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/) AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"history_name\") GROUP BY destination_name, workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  },
  {
   "title": "Average Staging-Time per Destination and Workflow",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_destination_name: $tag_workflow_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"sum\") FROM (SELECT sum(\"value\") FROM \"staging_time\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.DestinationComparisonBenchmark\\'>' AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/) AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\") WHERE $timeFilter GROUP BY benchmark_uuid, destination_name, workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Staging-Time per Destination and Job",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "staging_time",
     "query": "SELECT min(\"value\"), max(\"value\"), mean(\"value\"), stddev(\"value\") FROM (SELECT value FROM \"staging_time\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.DestinationComparisonBenchmark\\'>' AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/) AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"history_name\") GROUP BY destination_name, workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  },
  {
   "title": "Average Staging-Time per Destination and Job",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_destination_name: $tag_workflow_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") FROM (SELECT value FROM \"staging_time\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.DestinationComparisonBenchmark\\'>' AND \"benchmark_uuid\" =~ /$selected_benchmark_uuid/ AND \"workflow_name\" =~ /$selected_workflow_name/ AND \"destination_name\" =~ /$selected_destination_name/) AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"history_name\") WHERE $timeFilter GROUP BY destination_name, workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}