{
 "title": "Burst Benchmarks",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Workflow Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_benchmark_uuid: $col",
     "groupBy": [
      { "params": [ "benchmark_uuid" ], "type": "tag" }
     ],
     "measurement": "workflow_status",
     "query": "SELECT success, error FROM (SELECT count(\"value\") as success FROM \"workflow_status\" WHERE (\"value\" = 'success') AND $timeFilter GROUP BY \"benchmark_uuid\"), (SELECT count(\"value\") as error FROM \"workflow_status\" WHERE (\"value\" = 'error')  AND $timeFilter GROUP BY \"benchmark_uuid\") GROUP BY benchmark_uuid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "value", "operator": "=", "value": "error" }
     ]
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Runtimes",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "staging_time",
     "query": "SELECT sum(\"value\") FROM \"runtime_seconds\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.BurstBenchmark\\'>') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  },
  {
   "title": "Runtime per Benchmark and Workflow",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "alias": "$tag_ benchmark_uuid: $tag_workflow_name",
     "measurement": "runtime_seconds",
     "query": "SELECT median(\"sum\"), mean(\"sum\"), max(\"sum\"), min(\"sum\") FROM (SELECT sum(\"value\") FROM \"runtime_seconds\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.BurstBenchmark\\'>') AND $timeFilter GROUP BY \"workflow_name\", \"benchmark_uuid\", \"history_name\") WHERE $timeFilter GROUP BY \"benchmark_uuid\", \"workflow_name\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.BurstBenchmark'>"
      }
     ]
    }
   ]
  },
  {
   "title": "Runtime distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "staging_time",
     "query": "SELECT sum FROM (SELECT sum(\"value\") FROM \"runtime_seconds\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.BurstBenchmark\\'>') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  },
  { "title": "CPU Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU-Usage",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "cpuacct.usage",
     "query": "SELECT sum(\"value\") FROM \"cpuacct.usage\" WHERE (\"benchmark_type\" = '<class \\'benchmark.BurstBenchmark\\'>') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU-Usage per Benchmark and Workflow",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "cpuacct.usage",
     "query": "SELECT median(\"sum\"), mean(\"sum\"), max(\"sum\"), min(\"sum\") FROM (SELECT sum(\"value\") FROM \"cpuacct.usage\" WHERE (\"benchmark_type\" = '<class \\'benchmark.BurstBenchmark\\'>') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\") WHERE $timeFilter GROUP BY \"benchmark_uuid\", \"workflow_name\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  },
  { "title": "Staging Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Staging-Time per Workflow-Run",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"staging_time\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.BurstBenchmark\\'>') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Staging-Time per Benchmark and Workflow",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "staging_time",
     "query": "SELECT median(\"sum\"), mean(\"sum\"), max(\"sum\"), min(\"sum\") FROM (SELECT sum(\"value\") FROM \"staging_time\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.BurstBenchmark\\'>') AND $timeFilter GROUP BY \"workflow_name\", \"benchmark_uuid\", \"history_name\") WHERE $timeFilter GROUP BY \"benchmark_uuid\", \"workflow_name\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  },
  {
   "title": "Staging-Time distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "staging_time",
     "query": "SELECT sum FROM (SELECT sum(\"value\") FROM \"staging_time\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.BurstBenchmark\\'>') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  }
 ]
}