{
 "title": "Cold vs Warm Benchmarks",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Runtime for Cold-Run",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"runtime_seconds\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.ColdWarmBenchmark\\'>' AND \"run_type\" = 'cold') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Runtime for Warm-Run",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"runtime_seconds\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.ColdWarmBenchmark\\'>' AND \"run_type\" = 'warm') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Runtime for Warm-Run",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"sum\") FROM (SELECT sum(\"value\") FROM \"runtime_seconds\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.ColdWarmBenchmark\\'>' AND \"run_type\" = 'warm') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\") GROUP BY benchmark_uuid, workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Runtime for Cold-Run",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"sum\") FROM (SELECT sum(\"value\") FROM \"runtime_seconds\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.ColdWarmBenchmark\\'>' AND \"run_type\" = 'cold') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\") GROUP BY benchmark_uuid, workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Runtime Cold vs Warm per Workflow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Cold $tag_workflow_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"sum\") FROM (SELECT sum(\"value\") FROM \"runtime_seconds\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.ColdWarmBenchmark\\'>' AND \"run_type\" = 'cold') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\") WHERE $timeFilter GROUP BY benchmark_uuid, workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Warm $tag_workflow_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"sum\") FROM (SELECT sum(\"value\") FROM \"runtime_seconds\" WHERE (\"benchmark_type\" =  '<class \\'benchmark.ColdWarmBenchmark\\'>' AND \"run_type\" = 'warm') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\") WHERE $timeFilter GROUP BY benchmark_uuid, workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "CPU Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU-Usage for Cold-Run",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "cpuacct.usage",
     "query": "SELECT sum(\"value\") FROM \"cpuacct.usage\" WHERE (\"run_type\" = 'cold') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "cold" }
     ]
    }
   ]
  },
  {
   "title": "CPU-Usage for Warm-Run",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "cpuacct.usage",
     "query": "SELECT sum(\"value\") FROM \"cpuacct.usage\" WHERE (\"run_type\" = 'warm' AND \"benchmark_type\" = '<class \\'benchmark.ColdWarmBenchmark\\'>') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  },
  {
   "title": "Average CPU-Usage for Cold-Run per Benchmark",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "cpuacct.usage",
     "query": "SELECT mean(\"sum\") FROM (SELECT sum(\"value\") FROM \"cpuacct.usage\" WHERE (\"run_type\" = 'cold') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\") GROUP BY \"benchmark_uuid\", workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "cold" }
     ]
    }
   ]
  },
  {
   "title": "Average CPU-Usage for Warm-Run per Benchmark",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "cpuacct.usage",
     "query": "SELECT mean(\"sum\") FROM (SELECT sum(\"value\") FROM \"cpuacct.usage\" WHERE (\"run_type\" = 'warm' AND \"benchmark_type\" = '<class \\'benchmark.ColdWarmBenchmark\\'>') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\") GROUP BY \"benchmark_uuid\", workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  },
  {
   "title": "Average CPU-Time Cold vs Warm per Workflow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Cold $tag_workflow_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"sum\") FROM (SELECT sum(\"value\") FROM \"cpuacct.usage\" WHERE (\"run_type\" = 'cold') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\") WHERE $timeFilter GROUP BY \"benchmark_uuid\", workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Warm $tag_workflow_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"sum\") FROM (SELECT sum(\"value\") FROM \"cpuacct.usage\" WHERE (\"run_type\" = 'warm' AND \"benchmark_type\" = '<class \\'benchmark.ColdWarmBenchmark\\'>') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\") WHERE $timeFilter GROUP BY \"benchmark_uuid\", workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Staging Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Staging-Time for Cold-Run",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" },
      { "params": [ "benchmark_uuid" ], "type": "tag" },
      { "params": [ "history_name" ], "type": "tag" }
     ],
     "measurement": "staging_time",
     "query": "SELECT sum(\"value\") FROM \"staging_time\" WHERE (\"run_type\" = 'cold') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "cold" }
     ]
    }
   ]
  },
  {
   "title": "Staging-Time for Warm-Run",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "staging_time",
     "query": "SELECT sum(\"value\") FROM \"staging_time\" WHERE (\"run_type\" = 'warm' AND \"benchmark_type\" =  '<class \\'benchmark.ColdWarmBenchmark\\'>') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  },
  {
   "title": "Average Staging-Time for Cold-Run per Benchmark",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" },
      { "params": [ "benchmark_uuid" ], "type": "tag" },
      { "params": [ "history_name" ], "type": "tag" }
     ],
     "measurement": "staging_time",
     "query": "SELECT mean(\"sum\") FROM (SELECT sum(\"value\") FROM \"staging_time\" WHERE (\"run_type\" = 'cold') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\") GROUP BY \"benchmark_uuid\", workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "cold" }
     ]
    }
   ]
  },
  {
   "title": "Average Staging-Time for Warm-Run per Benchmark",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "alias": "CPU-Time per Workflow",
     "groupBy": [
      { "params": [ "benchmark_uid" ], "type": "tag" },
      { "params": [ "destination_name" ], "type": "tag" },
      { "params": [ "workflow_name" ], "type": "tag" }
     ],
     "measurement": "staging_time",
     "query": "SELECT mean(\"sum\") FROM (SELECT sum(\"value\") FROM \"staging_time\" WHERE (\"run_type\" = 'warm' AND \"benchmark_type\" =  '<class \\'benchmark.ColdWarmBenchmark\\'>') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\") GROUP BY benchmark_uuid, workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run_type", "operator": "=", "value": "warm" },
      {
       "condition": "AND",
       "key": "benchmark_type",
       "operator": "=",
       "value": "<class 'benchmark.ColdWarmBenchmark'>"
      }
     ]
    }
   ]
  },
  {
   "title": "Average Staging-Time Cold vs Warm per Workflow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Cold $tag_workflow_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"sum\") FROM (SELECT sum(\"value\") FROM \"staging_time\" WHERE (\"run_type\" = 'cold') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\") WHERE $timeFilter GROUP BY \"benchmark_uuid\", workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Warm $tag_workflow_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"sum\") FROM (SELECT sum(\"value\") FROM \"staging_time\" WHERE (\"run_type\" = 'warm' AND \"benchmark_type\" =  '<class \\'benchmark.ColdWarmBenchmark\\'>') AND $timeFilter GROUP BY \"destination_name\", \"workflow_name\", \"benchmark_uuid\", \"history_name\") WHERE $timeFilter GROUP BY benchmark_uuid, workflow_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}